# Generated by Django 3.2.9 on 2022-01-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0004_auto_20220111_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
