# Generated by Django 3.2.9 on 2022-01-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0007_auto_20220111_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Mat',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
