# Generated by Django 3.2.9 on 2022-01-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mat', '0011_alter_mat_sacco_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mat',
            name='sacco_name',
            field=models.CharField(max_length=30),
        ),
    ]
